version: '3.8'

services:
  postgres_server:
    image: postgres:15.1-alpine
    container_name: postgres_server
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi_tutorial
      - POSTGRES_PASSWORD=fastapi_tutorial
      - POSTGRES_DB=fastapi_tutorial

volumes:
  postgres_data: